#smolvlm_model.py
from transformers import AutoProcessor, AutoModelForImageTextToText
from PIL import Image
from pathlib import Path
import torch
import json

# Path to the locally downloaded SmolVLM2 model
model_path = "E:/Software-Projekte/SmolVLM/SmolVLM2-2.2B-Instruct"

# Load processor and model
processor = AutoProcessor.from_pretrained(model_path)
model = AutoModelForImageTextToText.from_pretrained(
    model_path,
    torch_dtype=torch.float16,        # float16 is optimal for RTX 3080 Ti
    _attn_implementation="eager"      # use eager mode if flash-attn is not installed
).to("cuda")

model.eval()  # Set model to evaluation mode


def infer_sequence(sequence_path: Path) -> str:
    """
    Performs inference with SmolVLM2 on a sequence of OCR-annotated character images.

    Each token in the sequence is expected to be a dictionary with:
    - "id"   : integer index
    - "ocr"  : recognized Chinese character (str)
    - "img"  : relative image path (str)

    The function constructs an interleaved input sequence (text + image) for the model,
    asking it to find meaningful word spans.

    Args:
        sequence_path (Path): Path to a JSON file with OCR+image tokens.

    Returns:
        str: The raw decoded string generated by the model.
    """
    # Load the sequence file
    with sequence_path.open("r", encoding="utf-8") as f:
        sequence = json.load(f)

    content = []
    for token in sequence:
        ocr = token["ocr"]
        image_path = (sequence_path.parent / token["img"]).resolve()
        image = Image.open(image_path).convert("RGB")

        # Append OCR and corresponding image as interleaved inputs
        content.append({"type": "text", "text": f"OCR: {ocr}"})
        content.append({"type": "image", "image": image})

    # Append the user instruction to the model
    # Replace the final instruction with a request for structured JSON output
    # Add final instruction for the model
    '''
    content.append({
        "type": "text",
        "text": (
            "You are given a sequence of single-character Chinese tokens, "
            "each with its corresponding OCR result and image. "
            "Please identify all potential multi-character words (word spans) "
            "that can be formed from this sequence.\n\n"
            "Return the result as a JSON object matching the following format:\n"
            "{\n"
            '  "results": [\n'
            "    {\n"
            '      "span": [start_index, ..., end_index],\n'
            '      "candidates": [\n'
            '        {"word": "string", "confidence": float},\n'
            "        ...\n"
            "      ]\n"
            "    },\n"
            "    ...\n"
            "  ]\n"
            "}\n\n"
            "Only return the JSON object. The first token in the sequence has index 0."
        )
    })
    '''
    content.append({
        "type": "text",
        "text": (
            "What word do these chinese characters represent?"
        )
    })


    messages = [{"role": "user", "content": content}]

    # Tokenize using chat template
    inputs = processor.apply_chat_template(
        messages,
        add_generation_prompt=True,
        tokenize=True,
        return_dict=True,
        return_tensors="pt"
    ).to(model.device, dtype=torch.float16)

    # Generate response
    with torch.no_grad():
        generated_ids = model.generate(**inputs, do_sample=False, max_new_tokens=128) #512 

    return processor.batch_decode(generated_ids, skip_special_tokens=True)[0].strip()






